const questions = [
  {
    id: 1,
    q: "allumer",
    translation: "to turn on",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 2,
    q: "le bain",
    translation: "the bath",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 3,
    q: "la boîte (en carton)",
    translation: "the (cardboard) box",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 4,
  //   q: "le centre de recyclage",
  //   translation: "the recycling centre",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 5,
    q: "le chômage",
    translation: "unemployment",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 6,
    q: "le chauffage central",
    translation: "the central heating",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 7,
    q: "cultiver",
    translation: "to grow",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 8,
    q: "en danger",
    translation: "in danger",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 9,
    q: "les déchets (masculin)",
    translation: "the rubbish",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 10,
    q: "détruire",
    translation: "to destroy",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 11,
  //   q: "disparaître",
  //   translation: "to disappear",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 12,
    q: "le sans-abri",
    translation: "the homeless person",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 13,
    q: "sauver",
    translation: "to save",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 14,
    q: "utiliser",
    translation: "to use",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 15,
    q: "la douche",
    translation: "the shower",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 16,
    q: "l'environnement",
    translation: "the environment",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 17,
    q: "éteindre",
    translation: "to turn off",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 18,
    q: "faire du recyclage",
    translation: "to recycle",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 19,
    q: "gaspiller",
    translation: "to waste",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 20,
  //   q: "l'inondation (féminin)",
  //   translation: "the flood",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 21,
    q: "jeter",
    translation: "to throw away",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 22,
    q: "les ordures (féminin)",
    translation: "rubbish",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 23,
    q: "la pauvreté",
    translation: "poverty",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 24,
    q: "le pétrole",
    translation: "oil",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 25,
    q: "la piste cyclable",
    translation: "the cycle route",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 26,
    q: "pollué",
    translation: "polluted",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 27,
    q: "la poubelle",
    translation: "the dustbin",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 28,
  //   q: "protéger",
  //   translation: "to protect",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 29,
    q: "le réchauffement de la Terre",
    translation: "global warming",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 30,
    q: "le robinet",
    translation: "the tap",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 31,
    q: "le sac en plastique",
    translation: "the plastic bag",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 32,
    q: "Vous pouvez utiliser la même lettre plus d'une fois.",
    translation: "You can use the same letter more than once.",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 33,
    q: "C’est quelle personne ?",
    translation: "Which person is it? ",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 34,
    q: "Ecrivez le nom de la bonne personne.",
    translation: "Write the name of the correct person.",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 35,
    q: "C'est qui ?",
    translation: "Who is it?",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 36,
    q: "Choisissez deux phrases qui sont vraies.",
    translation: "Choose two correct sentences",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 37,
  //   q: "Choisissez la réponse correcte",
  //   translation: "Choose the correct answer",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 38,
    q: "Choisissez la bonne réponse",
    translation: "Choose the correct answer",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 39,
    q: "Complétez … en français.",
    translation: "Complete ... in French",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 40,
    q: "Complétez la grille.",
    translation: "Complete the grid",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 41,
    q: "Complétez le texte suivant avec les mots de la liste ci-dessous.",
    translation: "Complete the following text with words from the list below.",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 42,
    q: "Complétez les phrases avec les mots de la liste.",
    translation: "Complete the sentences with words from the list.",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 43,
    q: "Décidez si c’est Vrai (V), Faux (F) ou Pas Mentionné (PM). Ecrivez V, F ou PM.",
    translation:
      "Decide if it is True (V), False (F) or Not Mentioned (PM). Write V, F or PM.",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 44,
    q: "Donnez deux détails.",
    translation: "Give two details",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 45,
    q: "Ecoutez ce passage",
    translation: "Listen to this passage",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 46,
    q: "Ecoutez cette conversation",
    translation: "Listen to this conversation",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 47,
  //   q: "Ecoutez cette interview",
  //   translation: "Listen to this interview",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 48,
    q: "Ecoutez ce reportage…",
    translation: "Listen to this report",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 49,
    q: "Ecrivez la bonne lettre dans chaque case.",
    translation: "Write the correct letter in each box",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 50,
    q: "Ecrivez la bonne lettre dans la case.",
    translation: "Write the correct letter in the box",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 51,
    q: "Ecrivez les bonnes lettres dans les cases.",
    translation: "Write the correct letters in the boxes",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 52,
    q: "Identifiez la bonne personne.",
    translation: "Identify the correct person",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 53,
    q: "Il n’est pas nécessaire d’écrire en phrases complètes.",
    translation: "It is not necessary to write in full sentences",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 54,
    q: "Lisez ...",
    translation: "Read ...",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 55,
    q: "Mentionnez un aspect positif/négatif",
    translation: "Mention a positive/negative aspect",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 56,
    q: "Mentionnez un avantage/inconvénient.",
    translation: "Mention an advantage/disadvantage",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 57,
    q: "Pour une opinion négative, écrivez N",
    translation: "For a negative opinion, write N",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 58,
    q: "Pour une opinion positive, écrivez P",
    translation: "For a positive opinion, write P",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 59,
    q: "Pour une opinion positive et négative, écrivez P+N",
    translation: "For a positive and negative opinion, write P+N",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 60,
    q: "Quelle est la réponse correcte ?",
    translation: "Which is the correct answer?",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 61,
    q: "Qui...?",
    translation: "Who...?",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 62,
    q: "Remplissez les blancs.",
    translation: "Fill in the blanks",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 63,
    q: "Répondez à ces questions.",
    translation: "Answer these questions",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 64,
  //   q: "Répondez (aux questions) en français.",
  //   translation: "Answer (the questions) in French",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 65,
    q: "Ce qui est important pour moi dans la vie, c'est d'abord...",
    translation: "The most important thing in life for me is firstly...",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 66,
    q: "Les animaux (masculin)",
    translation: "animals",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 67,
    q: "Ensuite, c'est...",
    translation: "Then, it is...",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 68,
  //   q: "le sport",
  //   translation: "sport",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 69,
    q: "La musique",
    translation: "Music",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 70,
  //   q: "ma santé",
  //   translation: "my health",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 71,
    q: "ma famille",
    translation: "my family",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 72,
    q: "l'argent (masculin)",
    translation: "money",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 73,
  //   q: "mes études",
  //   translation: "my studies",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 74,
    q: "mes amis",
    translation: "my friends",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 75,
    q: "Ce qui me préoccupe le plus c'est...",
    translation: "What worries me most is...",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: 76,
  //   q: "Ce qui m'inquiète le plus, c'est ...",
  //   translation: "What worries me most is...",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },
  {
    id: 77,
    q: "l'état (masculin) de la Terre",
    translation: "the state of the planet",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 78,
    q: "le réchauffement climatique",
    translation: "global warming",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 79,
    q: "la pauvreté dans le monde",
    translation: "world poverty",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 80,
    q: "l'injustice (f)",
    translation: "injustice",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 81,
    q: "les sans-abris",
    translation: "homeless people",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 82,
    q: "à part tout cela",
    translation: "apart from all that",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 83,
    q: "bien que (+ subjunctive)",
    translation: "although",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 84,
    q: "ceci dit",
    translation: "that said,",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 85,
    q: "comme ça ...",
    translation: "in this way",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 86,
    q: "du coup, ...",
    translation: "as a result ...",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 87,
    q: "en ce qui concerne ...",
    translation: "as far as ... is concerned",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 88,
    q: "en même temps",
    translation: "at the same time",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 89,
    q: "en train de",
    translation: "in the process of (doing)",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 90,
    q: "il s'agit de",
    translation: "it's about",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 91,
    q: "pas mal de",
    translation: "quite a lot of",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 92,
    q: "quotidiennement",
    translation: "daily",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 93,
    q: "tel que, telle que, tels que, telles que",
    translation: "such as",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 94,
    q: "tout le monde",
    translation: "everyone",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 95,
    q: "il y a du pour et du contre",
    translation: "There are pros and cons",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 96,
    q: "D'un côté, ça ...",
    translation: "On the one hand it...",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 97,
    q: "les personnes qui sont emprisonnées à tort",
    translation: "people who have been wrongly imprisoned",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 98,
    q: "les enfants qui n'ont pas assez à manger",
    translation: "children who don't have enough to eat",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 99,
    q: "On peut..",
    translation: "you can...",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 100,
    q: "Il est possible de ...",
    translation: "It is possible to...",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 101,
    q: "parrainer un enfant en Afrique",
    translation: "sponsor a child in Africa",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 102,
    q: "faire un don à une association caritative",
    translation: "donate to a charity",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 103,
    q: "faire du bénévolat",
    translation: "do voluntary work",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 104,
    q: "Il faut ...",
    translation: "We must/you have to ...",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 105,
    q: "lutter contre la faim",
    translation: "fight against hunger/famine",
    options: ["yes", "no"],
    answer: 0,
  },
  {
    id: 106,
    q: "lancer des pétitions",
    translation: "launch petitions",
    options: ["yes", "no"],
    answer: 0,
  },
  // {
  //   id: [],
  //   q: "exampleToCopy",
  //   translation: "",
  //   options: ["yes", "no"],
  //   answer: 0,
  // },




  //example of an image-based question
  // {
  //   id: 11,
  //   q: "How many squares are showing in this pic?",
  //   options: ["3", "2", "1"],
  //   answer: 2,
  //   img: "img/square.jpg"
  //   }
];

